//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisGmp.DIT._1
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", ConfigurationName = "SmevEndpointFacadeWs")]
    public interface SmevEndpointFacadeWs
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CheckRequestResponses();

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task CheckRequestResponsesAsync();

        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RedeliverSupplierRequestResponse RedeliverSupplierRequest(RedeliverSupplierRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<RedeliverSupplierRequestResponse> RedeliverSupplierRequestAsync(RedeliverSupplierRequest request);

        // CODEGEN: Контракт генерации сообщений с операцией SendRequest не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SendRequestResponse SendRequest(SendRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<SendRequestResponse> SendRequestAsync(SendRequest request);

        // CODEGEN: Контракт генерации сообщений с операцией SendResponseRequestRejected не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SendResponseRequestRejectedResponse SendResponseRequestRejected(SendResponseRequestRejected request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<SendResponseRequestRejectedResponse> SendResponseRequestRejectedAsync(SendResponseRequestRejected request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CheckIncomingRequests();

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task CheckIncomingRequestsAsync();

        // CODEGEN: Контракт генерации сообщений с операцией GetSupplierRequestAttachmentsInfo не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GetSupplierRequestAttachmentsInfoResponse GetSupplierRequestAttachmentsInfo(GetSupplierRequestAttachmentsInfo request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetSupplierRequestAttachmentsInfoResponse> GetSupplierRequestAttachmentsInfoAsync(GetSupplierRequestAttachmentsInfo request);

        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RedeliverConsumerResponseResponse RedeliverConsumerResponse(RedeliverConsumerResponse request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<RedeliverConsumerResponseResponse> RedeliverConsumerResponseAsync(RedeliverConsumerResponse request);

        // CODEGEN: Контракт генерации сообщений с операцией SendResponseRequestStatus не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SendResponseRequestStatusResponse SendResponseRequestStatus(SendResponseRequestStatus1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<SendResponseRequestStatusResponse> SendResponseRequestStatusAsync(SendResponseRequestStatus1 request);

        // CODEGEN: Контракт генерации сообщений с операцией GenerateMark не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GenerateMarkResponse1 GenerateMark(GenerateMark request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<GenerateMarkResponse1> GenerateMarkAsync(GenerateMark request);

        // CODEGEN: Контракт генерации сообщений с операцией SendResponse не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SendResponseResponse SendResponse(SendResponse request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<SendResponseResponse> SendResponseAsync(SendResponse request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RedeliverSupplierRequest", WrapperNamespace = "http://fors.com/smev3/exchange/facade/v1.0", IsWrapped = true)]
    public partial class RedeliverSupplierRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;

        public RedeliverSupplierRequest()
        {
        }

        public RedeliverSupplierRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RedeliverSupplierRequestResponse", WrapperNamespace = "http://fors.com/smev3/exchange/facade/v1.0", IsWrapped = true)]
    public partial class RedeliverSupplierRequestResponse
    {

        public RedeliverSupplierRequestResponse()
        {
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class sendRequestRequest
    {

        private string endpointCodeField;

        private string endSystemCodeField;

        private bool isTestField;

        private bool isTestFieldSpecified;

        private string transactionCodeField;

        private string referenceMessageIdField;

        private System.DateTime eOLField;

        private bool eOLFieldSpecified;

        private data dataField;

        private data personalSignatureField;

        private wsOutboundAttachmentType[] attachmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string EndpointCode
        {
            get
            {
                return this.endpointCodeField;
            }
            set
            {
                this.endpointCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string EndSystemCode
        {
            get
            {
                return this.endSystemCodeField;
            }
            set
            {
                this.endSystemCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public bool IsTest
        {
            get
            {
                return this.isTestField;
            }
            set
            {
                this.isTestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTestSpecified
        {
            get
            {
                return this.isTestFieldSpecified;
            }
            set
            {
                this.isTestFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string TransactionCode
        {
            get
            {
                return this.transactionCodeField;
            }
            set
            {
                this.transactionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string ReferenceMessageId
        {
            get
            {
                return this.referenceMessageIdField;
            }
            set
            {
                this.referenceMessageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public System.DateTime EOL
        {
            get
            {
                return this.eOLField;
            }
            set
            {
                this.eOLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EOLSpecified
        {
            get
            {
                return this.eOLFieldSpecified;
            }
            set
            {
                this.eOLFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public data Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public data PersonalSignature
        {
            get
            {
                return this.personalSignatureField;
            }
            set
            {
                this.personalSignatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public wsOutboundAttachmentType[] Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class data
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class sendResponseRequest
    {

        private string originalMessageIdField;

        private data dataField;

        private wsOutboundAttachmentType[] attachmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string OriginalMessageId
        {
            get
            {
                return this.originalMessageIdField;
            }
            set
            {
                this.originalMessageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public data Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public wsOutboundAttachmentType[] Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class wsOutboundAttachmentType
    {

        private string externalContentIdField;

        private string attachmentIdField;

        private string fileNameField;

        private string mimeTypeField;

        private byte[] signatureField;

        private byte[] digestField;

        private byte[] contentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string ExternalContentId
        {
            get
            {
                return this.externalContentIdField;
            }
            set
            {
                this.externalContentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string AttachmentId
        {
            get
            {
                return this.attachmentIdField;
            }
            set
            {
                this.attachmentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 4)]
        public byte[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 5)]
        public byte[] Digest
        {
            get
            {
                return this.digestField;
            }
            set
            {
                this.digestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 6)]
        public byte[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://voskhod.ru/transaction-marker")]
    public partial class marker
    {

        private string transactionUUIDField;

        private string transactionCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string TransactionUUID
        {
            get
            {
                return this.transactionUUIDField;
            }
            set
            {
                this.transactionUUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string TransactionCode
        {
            get
            {
                return this.transactionCodeField;
            }
            set
            {
                this.transactionCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://endpoints.transactionmarker.voskhod.ru/")]
    public partial class generateMarkResponse
    {

        private marker returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public marker @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://voskhod.ru/transaction-marker")]
    public partial class FRGUInformation
    {

        private string fRGUInteractionPartisipantCodeField;

        private string fRGUServiceCodeField;

        private string fRGUServiceDescriptionField;

        private string fRGUServiceRecipientDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string FRGUInteractionPartisipantCode
        {
            get
            {
                return this.fRGUInteractionPartisipantCodeField;
            }
            set
            {
                this.fRGUInteractionPartisipantCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string FRGUServiceCode
        {
            get
            {
                return this.fRGUServiceCodeField;
            }
            set
            {
                this.fRGUServiceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string FRGUServiceDescription
        {
            get
            {
                return this.fRGUServiceDescriptionField;
            }
            set
            {
                this.fRGUServiceDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string FRGUServiceRecipientDescription
        {
            get
            {
                return this.fRGUServiceRecipientDescriptionField;
            }
            set
            {
                this.fRGUServiceRecipientDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class generateMarkRequest
    {

        private string endpointCodeField;

        private FRGUInformation fRGUInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string EndpointCode
        {
            get
            {
                return this.endpointCodeField;
            }
            set
            {
                this.endpointCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public FRGUInformation FRGUInformation
        {
            get
            {
                return this.fRGUInformationField;
            }
            set
            {
                this.fRGUInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class RequestStatusParameterType
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class getAttachmentsInfoRequest
    {

        private string messageIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class requestRejected
    {

        private rejectCodeEnum rejectionReasonCodeField;

        private string rejectionReasonDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public rejectCodeEnum RejectionReasonCode
        {
            get
            {
                return this.rejectionReasonCodeField;
            }
            set
            {
                this.rejectionReasonCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string RejectionReasonDescription
        {
            get
            {
                return this.rejectionReasonDescriptionField;
            }
            set
            {
                this.rejectionReasonDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public enum rejectCodeEnum
    {

        /// <remarks/>
        ACCESS_DENIED,

        /// <remarks/>
        NO_DATA,

        /// <remarks/>
        UNKNOWN_REQUEST_DESCRIPTION,

        /// <remarks/>
        FAILURE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class sendResponseRequestRejectedRequest
    {

        private string originalMessageIdField;

        private requestRejected requestRejectedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string OriginalMessageId
        {
            get
            {
                return this.originalMessageIdField;
            }
            set
            {
                this.originalMessageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public requestRejected RequestRejected
        {
            get
            {
                return this.requestRejectedField;
            }
            set
            {
                this.requestRejectedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class smevEndpointFacadeWsResponse
    {

        private string messageIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendRequest", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public sendRequestRequest SendRequest1;

        public SendRequest()
        {
        }

        public SendRequest(sendRequestRequest SendRequest1)
        {
            this.SendRequest1 = SendRequest1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendRequestResponse", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        public smevEndpointFacadeWsResponse SendRequestResponse1;

        public SendRequestResponse()
        {
        }

        public SendRequestResponse(smevEndpointFacadeWsResponse SendRequestResponse1)
        {
            this.SendRequestResponse1 = SendRequestResponse1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendResponseRequestRejected
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendResponseRequestRejected", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public sendResponseRequestRejectedRequest SendResponseRequestRejected1;

        public SendResponseRequestRejected()
        {
        }

        public SendResponseRequestRejected(sendResponseRequestRejectedRequest SendResponseRequestRejected1)
        {
            this.SendResponseRequestRejected1 = SendResponseRequestRejected1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendResponseRequestRejectedResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public smevEndpointFacadeWsResponse SendResponseResponse;

        public SendResponseRequestRejectedResponse()
        {
        }

        public SendResponseRequestRejectedResponse(smevEndpointFacadeWsResponse SendResponseResponse)
        {
            this.SendResponseResponse = SendResponseResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class getAttachmentsInfoResultMessageAttachmentInfo
    {

        private string idField;

        private string attachmentIdField;

        private string mimeTypeField;

        private string fileNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string attachmentId
        {
            get
            {
                return this.attachmentIdField;
            }
            set
            {
                this.attachmentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSupplierRequestAttachmentsInfo
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSupplierRequestAttachmentsInfo", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public getAttachmentsInfoRequest GetSupplierRequestAttachmentsInfo1;

        public GetSupplierRequestAttachmentsInfo()
        {
        }

        public GetSupplierRequestAttachmentsInfo(getAttachmentsInfoRequest GetSupplierRequestAttachmentsInfo1)
        {
            this.GetSupplierRequestAttachmentsInfo1 = GetSupplierRequestAttachmentsInfo1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetSupplierRequestAttachmentsInfoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetSupplierRequestAttachmentsInfoResponse", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageAttachmentInfo", IsNullable = false)]
        public getAttachmentsInfoResultMessageAttachmentInfo[] GetSupplierRequestAttachmentsInfoResponse1;

        public GetSupplierRequestAttachmentsInfoResponse()
        {
        }

        public GetSupplierRequestAttachmentsInfoResponse(getAttachmentsInfoResultMessageAttachmentInfo[] GetSupplierRequestAttachmentsInfoResponse1)
        {
            this.GetSupplierRequestAttachmentsInfoResponse1 = GetSupplierRequestAttachmentsInfoResponse1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RedeliverConsumerResponse", WrapperNamespace = "http://fors.com/smev3/exchange/facade/v1.0", IsWrapped = true)]
    public partial class RedeliverConsumerResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;

        public RedeliverConsumerResponse()
        {
        }

        public RedeliverConsumerResponse(string arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RedeliverConsumerResponseResponse", WrapperNamespace = "http://fors.com/smev3/exchange/facade/v1.0", IsWrapped = true)]
    public partial class RedeliverConsumerResponseResponse
    {

        public RedeliverConsumerResponseResponse()
        {
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fors.com/smev3/exchange/facade/v1.0")]
    public partial class SendResponseRequestStatus
    {

        private string originalMessageIdField;

        private int statusCodeField;

        private RequestStatusParameterType[] statusParameterField;

        private string statusDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string OriginalMessageId
        {
            get
            {
                return this.originalMessageIdField;
            }
            set
            {
                this.originalMessageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatusParameter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public RequestStatusParameterType[] StatusParameter
        {
            get
            {
                return this.statusParameterField;
            }
            set
            {
                this.statusParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendResponseRequestStatus1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public SendResponseRequestStatus SendResponseRequestStatus;

        public SendResponseRequestStatus1()
        {
        }

        public SendResponseRequestStatus1(SendResponseRequestStatus SendResponseRequestStatus)
        {
            this.SendResponseRequestStatus = SendResponseRequestStatus;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendResponseRequestStatusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public smevEndpointFacadeWsResponse SendResponseResponse;

        public SendResponseRequestStatusResponse()
        {
        }

        public SendResponseRequestStatusResponse(smevEndpointFacadeWsResponse SendResponseResponse)
        {
            this.SendResponseResponse = SendResponseResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GenerateMark
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GenerateMark", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public generateMarkRequest GenerateMark1;

        public GenerateMark()
        {
        }

        public GenerateMark(generateMarkRequest GenerateMark1)
        {
            this.GenerateMark1 = GenerateMark1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GenerateMarkResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public generateMarkResponse generateMarkResponse;

        public GenerateMarkResponse1()
        {
        }

        public GenerateMarkResponse1(generateMarkResponse generateMarkResponse)
        {
            this.generateMarkResponse = generateMarkResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendResponse", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public sendResponseRequest SendResponse1;

        public SendResponse()
        {
        }

        public SendResponse(sendResponseRequest SendResponse1)
        {
            this.SendResponse1 = SendResponse1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SendResponseResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendResponseResponse", Namespace = "http://fors.com/smev3/exchange/facade/v1.0", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public smevEndpointFacadeWsResponse SendResponseResponse1;

        public SendResponseResponse()
        {
        }

        public SendResponseResponse(smevEndpointFacadeWsResponse SendResponseResponse1)
        {
            this.SendResponseResponse1 = SendResponseResponse1;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmevEndpointFacadeWsChannel : SmevEndpointFacadeWs, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmevEndpointFacadeWsClient : System.ServiceModel.ClientBase<SmevEndpointFacadeWs>, SmevEndpointFacadeWs
    {

        public SmevEndpointFacadeWsClient()
        {
        }

        public SmevEndpointFacadeWsClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public SmevEndpointFacadeWsClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SmevEndpointFacadeWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SmevEndpointFacadeWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public void CheckRequestResponses()
        {
            base.Channel.CheckRequestResponses();
        }

        public System.Threading.Tasks.Task CheckRequestResponsesAsync()
        {
            return base.Channel.CheckRequestResponsesAsync();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedeliverSupplierRequestResponse SmevEndpointFacadeWs.RedeliverSupplierRequest(RedeliverSupplierRequest request)
        {
            return base.Channel.RedeliverSupplierRequest(request);
        }

        public void RedeliverSupplierRequest(string arg0)
        {
            RedeliverSupplierRequest inValue = new RedeliverSupplierRequest();
            inValue.arg0 = arg0;
            RedeliverSupplierRequestResponse retVal = ((SmevEndpointFacadeWs)(this)).RedeliverSupplierRequest(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedeliverSupplierRequestResponse> SmevEndpointFacadeWs.RedeliverSupplierRequestAsync(RedeliverSupplierRequest request)
        {
            return base.Channel.RedeliverSupplierRequestAsync(request);
        }

        public System.Threading.Tasks.Task<RedeliverSupplierRequestResponse> RedeliverSupplierRequestAsync(string arg0)
        {
            RedeliverSupplierRequest inValue = new RedeliverSupplierRequest();
            inValue.arg0 = arg0;
            return ((SmevEndpointFacadeWs)(this)).RedeliverSupplierRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendRequestResponse SmevEndpointFacadeWs.SendRequest(SendRequest request)
        {
            return base.Channel.SendRequest(request);
        }

        public smevEndpointFacadeWsResponse SendRequest(sendRequestRequest SendRequest1)
        {
            SendRequest inValue = new SendRequest();
            inValue.SendRequest1 = SendRequest1;
            SendRequestResponse retVal = ((SmevEndpointFacadeWs)(this)).SendRequest(inValue);
            return retVal.SendRequestResponse1;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendRequestResponse> SmevEndpointFacadeWs.SendRequestAsync(SendRequest request)
        {
            return base.Channel.SendRequestAsync(request);
        }

        public System.Threading.Tasks.Task<SendRequestResponse> SendRequestAsync(sendRequestRequest SendRequest1)
        {
            SendRequest inValue = new SendRequest();
            inValue.SendRequest1 = SendRequest1;
            return ((SmevEndpointFacadeWs)(this)).SendRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendResponseRequestRejectedResponse SmevEndpointFacadeWs.SendResponseRequestRejected(SendResponseRequestRejected request)
        {
            return base.Channel.SendResponseRequestRejected(request);
        }

        public smevEndpointFacadeWsResponse SendResponseRequestRejected(sendResponseRequestRejectedRequest SendResponseRequestRejected1)
        {
            SendResponseRequestRejected inValue = new SendResponseRequestRejected();
            inValue.SendResponseRequestRejected1 = SendResponseRequestRejected1;
            SendResponseRequestRejectedResponse retVal = ((SmevEndpointFacadeWs)(this)).SendResponseRequestRejected(inValue);
            return retVal.SendResponseResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendResponseRequestRejectedResponse> SmevEndpointFacadeWs.SendResponseRequestRejectedAsync(SendResponseRequestRejected request)
        {
            return base.Channel.SendResponseRequestRejectedAsync(request);
        }

        public System.Threading.Tasks.Task<SendResponseRequestRejectedResponse> SendResponseRequestRejectedAsync(sendResponseRequestRejectedRequest SendResponseRequestRejected1)
        {
            SendResponseRequestRejected inValue = new SendResponseRequestRejected();
            inValue.SendResponseRequestRejected1 = SendResponseRequestRejected1;
            return ((SmevEndpointFacadeWs)(this)).SendResponseRequestRejectedAsync(inValue);
        }

        public void CheckIncomingRequests()
        {
            base.Channel.CheckIncomingRequests();
        }

        public System.Threading.Tasks.Task CheckIncomingRequestsAsync()
        {
            return base.Channel.CheckIncomingRequestsAsync();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetSupplierRequestAttachmentsInfoResponse SmevEndpointFacadeWs.GetSupplierRequestAttachmentsInfo(GetSupplierRequestAttachmentsInfo request)
        {
            return base.Channel.GetSupplierRequestAttachmentsInfo(request);
        }

        public getAttachmentsInfoResultMessageAttachmentInfo[] GetSupplierRequestAttachmentsInfo(getAttachmentsInfoRequest GetSupplierRequestAttachmentsInfo1)
        {
            GetSupplierRequestAttachmentsInfo inValue = new GetSupplierRequestAttachmentsInfo();
            inValue.GetSupplierRequestAttachmentsInfo1 = GetSupplierRequestAttachmentsInfo1;
            GetSupplierRequestAttachmentsInfoResponse retVal = ((SmevEndpointFacadeWs)(this)).GetSupplierRequestAttachmentsInfo(inValue);
            return retVal.GetSupplierRequestAttachmentsInfoResponse1;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetSupplierRequestAttachmentsInfoResponse> SmevEndpointFacadeWs.GetSupplierRequestAttachmentsInfoAsync(GetSupplierRequestAttachmentsInfo request)
        {
            return base.Channel.GetSupplierRequestAttachmentsInfoAsync(request);
        }

        public System.Threading.Tasks.Task<GetSupplierRequestAttachmentsInfoResponse> GetSupplierRequestAttachmentsInfoAsync(getAttachmentsInfoRequest GetSupplierRequestAttachmentsInfo1)
        {
            GetSupplierRequestAttachmentsInfo inValue = new GetSupplierRequestAttachmentsInfo();
            inValue.GetSupplierRequestAttachmentsInfo1 = GetSupplierRequestAttachmentsInfo1;
            return ((SmevEndpointFacadeWs)(this)).GetSupplierRequestAttachmentsInfoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedeliverConsumerResponseResponse SmevEndpointFacadeWs.RedeliverConsumerResponse(RedeliverConsumerResponse request)
        {
            return base.Channel.RedeliverConsumerResponse(request);
        }

        public void RedeliverConsumerResponse(string arg0)
        {
            RedeliverConsumerResponse inValue = new RedeliverConsumerResponse();
            inValue.arg0 = arg0;
            RedeliverConsumerResponseResponse retVal = ((SmevEndpointFacadeWs)(this)).RedeliverConsumerResponse(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedeliverConsumerResponseResponse> SmevEndpointFacadeWs.RedeliverConsumerResponseAsync(RedeliverConsumerResponse request)
        {
            return base.Channel.RedeliverConsumerResponseAsync(request);
        }

        public System.Threading.Tasks.Task<RedeliverConsumerResponseResponse> RedeliverConsumerResponseAsync(string arg0)
        {
            RedeliverConsumerResponse inValue = new RedeliverConsumerResponse();
            inValue.arg0 = arg0;
            return ((SmevEndpointFacadeWs)(this)).RedeliverConsumerResponseAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendResponseRequestStatusResponse SmevEndpointFacadeWs.SendResponseRequestStatus(SendResponseRequestStatus1 request)
        {
            return base.Channel.SendResponseRequestStatus(request);
        }

        public smevEndpointFacadeWsResponse SendResponseRequestStatus(SendResponseRequestStatus SendResponseRequestStatus1)
        {
            SendResponseRequestStatus1 inValue = new SendResponseRequestStatus1();
            inValue.SendResponseRequestStatus = SendResponseRequestStatus1;
            SendResponseRequestStatusResponse retVal = ((SmevEndpointFacadeWs)(this)).SendResponseRequestStatus(inValue);
            return retVal.SendResponseResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendResponseRequestStatusResponse> SmevEndpointFacadeWs.SendResponseRequestStatusAsync(SendResponseRequestStatus1 request)
        {
            return base.Channel.SendResponseRequestStatusAsync(request);
        }

        public System.Threading.Tasks.Task<SendResponseRequestStatusResponse> SendResponseRequestStatusAsync(SendResponseRequestStatus SendResponseRequestStatus)
        {
            SendResponseRequestStatus1 inValue = new SendResponseRequestStatus1();
            inValue.SendResponseRequestStatus = SendResponseRequestStatus;
            return ((SmevEndpointFacadeWs)(this)).SendResponseRequestStatusAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GenerateMarkResponse1 SmevEndpointFacadeWs.GenerateMark(GenerateMark request)
        {
            return base.Channel.GenerateMark(request);
        }

        public generateMarkResponse GenerateMark(generateMarkRequest GenerateMark1)
        {
            GenerateMark inValue = new GenerateMark();
            inValue.GenerateMark1 = GenerateMark1;
            GenerateMarkResponse1 retVal = ((SmevEndpointFacadeWs)(this)).GenerateMark(inValue);
            return retVal.generateMarkResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GenerateMarkResponse1> SmevEndpointFacadeWs.GenerateMarkAsync(GenerateMark request)
        {
            return base.Channel.GenerateMarkAsync(request);
        }

        public System.Threading.Tasks.Task<GenerateMarkResponse1> GenerateMarkAsync(generateMarkRequest GenerateMark1)
        {
            GenerateMark inValue = new GenerateMark();
            inValue.GenerateMark1 = GenerateMark1;
            return ((SmevEndpointFacadeWs)(this)).GenerateMarkAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendResponseResponse SmevEndpointFacadeWs.SendResponse(SendResponse request)
        {
            return base.Channel.SendResponse(request);
        }

        public smevEndpointFacadeWsResponse SendResponse(sendResponseRequest SendResponse1)
        {
            SendResponse inValue = new SendResponse();
            inValue.SendResponse1 = SendResponse1;
            SendResponseResponse retVal = ((SmevEndpointFacadeWs)(this)).SendResponse(inValue);
            return retVal.SendResponseResponse1;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendResponseResponse> SmevEndpointFacadeWs.SendResponseAsync(SendResponse request)
        {
            return base.Channel.SendResponseAsync(request);
        }

        public System.Threading.Tasks.Task<SendResponseResponse> SendResponseAsync(sendResponseRequest SendResponse1)
        {
            SendResponse inValue = new SendResponse();
            inValue.SendResponse1 = SendResponse1;
            return ((SmevEndpointFacadeWs)(this)).SendResponseAsync(inValue);
        }
    }
}