//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fors.ru/smev3/answer-service/wsdl", ConfigurationName="SmevAnswerService")]
public interface SmevAnswerService
{
    
    // CODEGEN: Контракт генерации сообщений с операцией GetResponseAnswer не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.fors.ru/smev3/answer-service/wsdl/SmevAnswerService/GetResponseAnswerR" +
        "equest", ReplyAction="http://www.fors.ru/smev3/answer-service/wsdl/SmevAnswerService/GetResponseAnswerR" +
        "esponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetResponseAnswerResponse1 GetResponseAnswer(GetResponseAnswerRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.fors.ru/smev3/answer-service/wsdl/SmevAnswerService/GetResponseAnswerR" +
        "equest", ReplyAction="http://www.fors.ru/smev3/answer-service/wsdl/SmevAnswerService/GetResponseAnswerR" +
        "esponse")]
    System.Threading.Tasks.Task<GetResponseAnswerResponse1> GetResponseAnswerAsync(GetResponseAnswerRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fors.ru/smev3/answer-service")]
public partial class GetResponseAnswerRequest
{
    
    private string messageIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string messageId
    {
        get
        {
            return this.messageIdField;
        }
        set
        {
            this.messageIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fors.ru/smev3/answer-service")]
public partial class AttachmentInfo
{
    
    private string idField;
    
    private string fileNameField;
    
    private string mimeTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string FileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string MimeType
    {
        get
        {
            return this.mimeTypeField;
        }
        set
        {
            this.mimeTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fors.ru/smev3/answer-service")]
public partial class GetResponseAnswerResponse
{
    
    private string requestStatusField;
    
    private string requestErrorField;
    
    private System.DateTime requestSendDateField;
    
    private bool requestSendDateFieldSpecified;
    
    private GetResponseAnswerResponseResponse responseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string RequestStatus
    {
        get
        {
            return this.requestStatusField;
        }
        set
        {
            this.requestStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string RequestError
    {
        get
        {
            return this.requestErrorField;
        }
        set
        {
            this.requestErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public System.DateTime RequestSendDate
    {
        get
        {
            return this.requestSendDateField;
        }
        set
        {
            this.requestSendDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequestSendDateSpecified
    {
        get
        {
            return this.requestSendDateFieldSpecified;
        }
        set
        {
            this.requestSendDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public GetResponseAnswerResponseResponse Response
    {
        get
        {
            return this.responseField;
        }
        set
        {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fors.ru/smev3/answer-service")]
public partial class GetResponseAnswerResponseResponse
{
    
    private string responseTypeField;
    
    private System.DateTime responseDateField;
    
    private System.Xml.XmlElement responseContentField;
    
    private AttachmentInfo[] attachmentField;
    
    private string asyncProcessingStatusCategoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string ResponseType
    {
        get
        {
            return this.responseTypeField;
        }
        set
        {
            this.responseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public System.DateTime ResponseDate
    {
        get
        {
            return this.responseDateField;
        }
        set
        {
            this.responseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public System.Xml.XmlElement ResponseContent
    {
        get
        {
            return this.responseContentField;
        }
        set
        {
            this.responseContentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public AttachmentInfo[] Attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string AsyncProcessingStatusCategory
    {
        get
        {
            return this.asyncProcessingStatusCategoryField;
        }
        set
        {
            this.asyncProcessingStatusCategoryField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetResponseAnswerRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.fors.ru/smev3/answer-service", Order=0)]
    public GetResponseAnswerRequest GetResponseAnswerRequest;
    
    public GetResponseAnswerRequest1()
    {
    }
    
    public GetResponseAnswerRequest1(GetResponseAnswerRequest GetResponseAnswerRequest)
    {
        this.GetResponseAnswerRequest = GetResponseAnswerRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetResponseAnswerResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.fors.ru/smev3/answer-service", Order=0)]
    public GetResponseAnswerResponse GetResponseAnswerResponse;
    
    public GetResponseAnswerResponse1()
    {
    }
    
    public GetResponseAnswerResponse1(GetResponseAnswerResponse GetResponseAnswerResponse)
    {
        this.GetResponseAnswerResponse = GetResponseAnswerResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SmevAnswerServiceChannel : SmevAnswerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SmevAnswerServiceClient : System.ServiceModel.ClientBase<SmevAnswerService>, SmevAnswerService
{
    
    public SmevAnswerServiceClient()
    {
    }
    
    public SmevAnswerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SmevAnswerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SmevAnswerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SmevAnswerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetResponseAnswerResponse1 SmevAnswerService.GetResponseAnswer(GetResponseAnswerRequest1 request)
    {
        return base.Channel.GetResponseAnswer(request);
    }
    
    public GetResponseAnswerResponse GetResponseAnswer(GetResponseAnswerRequest GetResponseAnswerRequest)
    {
        GetResponseAnswerRequest1 inValue = new GetResponseAnswerRequest1();
        inValue.GetResponseAnswerRequest = GetResponseAnswerRequest;
        GetResponseAnswerResponse1 retVal = ((SmevAnswerService)(this)).GetResponseAnswer(inValue);
        return retVal.GetResponseAnswerResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetResponseAnswerResponse1> SmevAnswerService.GetResponseAnswerAsync(GetResponseAnswerRequest1 request)
    {
        return base.Channel.GetResponseAnswerAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetResponseAnswerResponse1> GetResponseAnswerAsync(GetResponseAnswerRequest GetResponseAnswerRequest)
    {
        GetResponseAnswerRequest1 inValue = new GetResponseAnswerRequest1();
        inValue.GetResponseAnswerRequest = GetResponseAnswerRequest;
        return ((SmevAnswerService)(this)).GetResponseAnswerAsync(inValue);
    }
}
